apiVersion: v1
kind: Service
metadata:
  labels:
    app: clio-ui-service-acceptance
  name: clio-ui-service-acceptance
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: clio-ui-acceptance
  type: ClusterIP
