name: '- helper (sonar)'
on:
  workflow_call:
    inputs:
      tag_name:
        required: false
        type: string
        default: 'develop'
jobs:
  run-sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.tag_name || github.event.pull_request.head.ref }}
      - name: Get Project LCOV
        uses: actions/download-artifact@v4 # Updated deprecated @master parameter
        with:
          name: appLcov
          path: .
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7.1.0
        env:
          SONAR_TOKEN: ${{ secrets.METIS_FRONTEND_SONAR_TOKEN }}
        with:
          args:
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.organization=europeana
            -Dsonar.projectKey=europeana_clio-ui
            -Dsonar.test.inclusions=**/*.spec.ts
            -Dsonar.sources=src/app
            -Dsonar.exclusions=src/**/_mocked/**
            -Dsonar.javascript.lcov.reportPaths=./lcov.info
